name: Build and Push to ECR

on: 
  push: 
      branches: ["main"]

jobs:
  build: 
      runs-on: ubuntu-latest
      steps: 
          - name: Checkout the code
            uses: actions/checkout@v7
          - name: Trivy build
            uses: aquasecurity/trivy-action@v0.36.0
            with:
              scan-type: 'fs'
              severity: HIGH, CRITICAL
              exit-code: '1'
          - name: Build docker image
            run: docker build -t 267673636159.dkr.ecr.us-east-2.amazonaws.com/nginx-with-ping:v3
          - name: Scan Docker image
            uses: aquasecurity/trivy-action@v0.36.0
            with:
              image-ref: 267673636159.dkr.ecr.us-east-2.amazonaws.com/nginx-with-ping:v3
              format: 'table'
              severity: HIGH, CRITICAL
              exit-code: '1'
              ignore-unfixed: true
          - name: Pysh Docker Image to ECR
            run: echo "Pushes"
